### ISSUE TITLE
Error on Knitting GAReport.Rmd - object "gadata" not found 

### ISSUE THREAD

**Issue by beingPratap** [hezumartin/BDACaseStudyGA#2]
Error message:

```
Quitting from lines 29-32 (GAReport.Rmd) 
Error in nrow(gadata) : object 'gadata' not found
Calls: <Anonymous> ... eval -> gvisTable -> modifyList -> stopifnot -> nrow
Execution halted
```

Though gadata object is available in the scope on the Console terminal, I get this error on knitting the GAReport.Rmd file

**Comment by beingPratap** [comment]
Solved it; the issue is RStudio runs the KnitHTML in a different scope, and it does not have access to data objects in global scope, therefore you will need to separately load your .Rdata in the markdown file. Add this line at the top of GAReport.rmd -

```
load(file="../.RData")
```

**Comment by hezumartin** [comment]
Happy to see you could solve it.

Instead of trying to knit the rmd report, you should run the full code
at RunStudy.R (more specifically R/runcode.R).

---

Jesús Martín Calvo
Digital Analytics Consultant - Consultor de Analítica Digital

## www.jesusmartincalvo.com
